name = "EulerCharacteristic"
uuid = "2c1df2f5-4ab6-47a9-8339-2c9d55c0a52c"
authors = ["Vasily Postnicov <shamaz.mazum@gmail.com>"]
version = "0.1.3"

[compat]
julia = "^1.0"

[extras]
XUnit = "3e3c03f2-1a94-11e9-2981-050a4ca824ab"

[targets]
test = ["XUnit"]
